spring:
  resources:
    static-locations:
    - classpath:/mystatic/
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: hooliss-consumer
server:
  port: 5120

eureka:
  instance:
    instance-id: hooliss_consumer_one
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.232.36.244:7001/eureka
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
