spring:
  cloud:
    refresh:
      refreshable: none
  datasource:
    url: jdbc:mysql://192.168.43.52:8066/hooliss?useUnicode=true&characterEncoding=utf-8
    username: mycat
    password: 123456
  redis:
    database: 0
    host: 49.232.36.244
    port: 9736
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100ms
    password: myRedispd,.1218
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 111.229.128.116:9300
  application:
    name: hooliss-commodity-provider
eureka:
  instance:
    instance-id: commodity-provider-one
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.232.36.244:7001/eureka
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
server:
  port: 8001
